services:
  - type: cron
    name: olx-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "*/30 * * * *"  # La fiecare 30 de minute
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

